# Independent oracle for runtime/tests/test_crypto_more.cpp (writes tests/crypto_rsa_vectors.inc to stdout): RSA keys from Python's own big integers,
# Miller-Rabin primes from a fixed seed, PKCS#1 v1.5 (RFC 8017) SHA-1 signature of "abc".
import hashlib, random

rng = random.Random(0x52434F4D)

def is_probable_prime(n):
    if n < 2: return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0: return n == p
    d, s = n - 1, 0
    while d % 2 == 0: d //= 2; s += 1
    for _ in range(40):
        a = rng.randrange(2, n - 2)
        x = pow(a, d, n)
        if x in (1, n - 1): continue
        for _ in range(s - 1):
            x = pow(x, 2, n)
            if x == n - 1: break
        else:
            return False
    return True

def prime(bits, e):
    while True:
        p = rng.getrandbits(bits) | (1 << (bits - 1)) | (1 << (bits - 2)) | 1
        if is_probable_prime(p) and (p - 1) % e != 0: return p

def key(bits, e):
    while True:
        p, q = prime(bits // 2, e), prime(bits // 2, e)
        n = p * q
        if n.bit_length() == bits and p != q:
            d = pow(e, -1, (p - 1) * (q - 1))
            return n, d

def qw(v, count):  # QwNe: least significant qword first
    return [(v >> (64 * i)) & 0xFFFFFFFFFFFFFFFF for i in range(count)]

def arr(name, vals, kind="uint64_t", per=4):
    fmt = "0x%016XULL" if kind == "uint64_t" else "0x%02X"
    lines = []
    for i in range(0, len(vals), per):
        lines.append("    " + ", ".join(fmt % v for v in vals[i:i + per]) + ",")
    return "const %s %s[%d] = {\n%s\n};" % (kind, name, len(vals), "\n".join(lines))

out = ["// Generated by runtime/tests/crypto_rsa_oracle.py (Python big integers; seed 0x52434F4D). Not title data."]
# 1024-bit, e = 65537: plain modexp oracle.
n1, d1 = key(1024, 65537)
m1 = rng.getrandbits(1000)
c1 = pow(m1, 65537, n1)
out.append(arr("kRsa1024N", qw(n1, 16)))
out.append(arr("kRsa1024M", qw(m1, 16)))
out.append(arr("kRsa1024C", qw(c1, 16)))
# 1024-bit, e = 3.
n3, d3 = key(1024, 3)
m3 = rng.getrandbits(1020)
out.append(arr("kRsa1024e3N", qw(n3, 16)))
out.append(arr("kRsa1024e3M", qw(m3, 16)))
out.append(arr("kRsa1024e3C", qw(pow(m3, 3, n3), 16)))
# 2048-bit, e = 65537: PKCS#1 v1.5 signature of SHA-1("abc") with the DigestInfo NULL form.
n2, d2 = key(2048, 65537)
h = hashlib.sha1(b"abc").digest()
T = bytes([0x30, 0x21, 0x30, 0x09, 0x06, 0x05, 0x2B, 0x0E, 0x03, 0x02, 0x1A, 0x05, 0x00, 0x04, 0x14]) + h
k = 256
em = b"\x00\x01" + b"\xFF" * (k - 3 - len(T)) + b"\x00" + T
s = pow(int.from_bytes(em, "big"), d2, n2)
assert pow(s, 65537, n2) == int.from_bytes(em, "big")
out.append(arr("kRsa2048N", qw(n2, 32)))
out.append(arr("kSigAbcLe", list(s.to_bytes(k, "little")), "uint8_t", 16))
out.append(arr("kSha1Abc", list(h), "uint8_t", 20))
print("\n".join(out))
