#!/usr/bin/env bash
# R-comp - Agent 4 (PS5_Vulkan integration).
# SPDX-License-Identifier: GPL-3.0-or-later
#
# GLSL -> SPIR-V 1.0 (Vulkan 1.0 environment) -> C arrays.
#
#   draw_test/build-shaders.sh [OUT_DIR]     (default: draw_test/generated)
#
# The generated header is committed so the PS5 cross build needs no glslang;
# generated/SHADERS.lock records the tool version and the sha256 of every GLSL
# input and SPIR-V output. --check regenerates into a temporary directory and
# fails (exit 1) if the committed files differ.
set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
check=false
if [[ ${1:-} == --check ]]; then check=true; shift; fi
out=${1:-$here/generated}
$check && out=$(mktemp -d)
mkdir -p "$out"

command -v glslangValidator >/dev/null || { echo "BLOCKED: glslangValidator not found" >&2; exit 2; }
version=$(glslangValidator --version | head -n 1)

header="$out/draw_test_spirv.h"
{
    echo "/* Generated by gpu/vulkan/draw_test/build-shaders.sh - do not edit. */"
    echo "/* $version; --target-env vulkan1.0 (SPIR-V 1.0) */"
    echo "#include <stdint.h>"
} > "$header"
lock="$out/SHADERS.lock"
{
    echo "tool: $version"
    echo "flags: -V --target-env vulkan1.0"
} > "$lock"
for stage in vert frag; do
    src="$here/shaders/triangle.$stage"
    spv="$out/triangle.$stage.spv"
    glslangValidator -V --target-env vulkan1.0 -o "$spv" "$src" >/dev/null
    # SPIR-V header word 1 is the version: 0x00010000 for 1.0.
    ver=$(od -An -tx4 -j4 -N4 "$spv" | tr -d ' ')
    [[ $ver == 00010000 ]] || { echo "error: $spv is SPIR-V $ver, not 1.0" >&2; exit 1; }
    python3 - "$spv" "triangle_${stage}_spv" >> "$header" <<'PY'
import sys
data = open(sys.argv[1], "rb").read()
words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
print(f"static const uint32_t {sys.argv[2]}[{len(words)}] = {{")
for i in range(0, len(words), 6):
    print("   " + ", ".join(f"0x{w:08x}u" for w in words[i:i + 6]) + ",")
print("};")
PY
    echo "glsl $(sha256sum "$src" | cut -d' ' -f1) shaders/triangle.$stage" >> "$lock"
    echo "spirv $(sha256sum "$spv" | cut -d' ' -f1) triangle.$stage.spv (SPIR-V 1.0)" >> "$lock"
done
if $check; then
    rc=0
    for f in draw_test_spirv.h SHADERS.lock triangle.vert.spv triangle.frag.spv; do
        cmp -s "$out/$f" "$here/generated/$f" || { echo "differs: generated/$f" >&2; rc=1; }
    done
    rm -rf -- "$out"
    exit $rc
fi
cat "$lock"
