#!/bin/bash
# PS5 port frontend: compiles shaders/*.vert|*.frag to SPIR-V and writes fe_shaders.inc, the
# words as uint32_t arrays (fe_spv_<name>_<stage>).
# Copyright (C) 2026 Spyros
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail
cd "$(dirname "$0")"
GLSLANG_VALIDATOR=${GLSLANG_VALIDATOR:-glslangValidator}
OUT=fe_shaders.inc
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
{
  echo "// Generated by build_shaders.sh from shaders/: SPIR-V words. Do not edit."
  for src in shaders/*.vert shaders/*.frag; do
    base=$(basename "$src")
    name=${base%.*}
    stage=${base##*.}
    "$GLSLANG_VALIDATOR" -V --target-env vulkan1.1 -Ishaders -o "$TMP/$name.$stage.spv" "$src" >"$TMP/log" 2>&1 || { cat "$TMP/log" >&2; exit 1; }
    python3 - "$TMP/$name.$stage.spv" "fe_spv_${name}_${stage}" <<'PY'
import struct, sys
data = open(sys.argv[1], 'rb').read()
words = struct.unpack('<%dI' % (len(data) // 4), data)
print('static const uint32_t %s[] = {' % sys.argv[2])
for i in range(0, len(words), 8):
    print('\t' + ', '.join('0x%08x' % w for w in words[i:i + 8]) + ',')
print('};')
PY
  done
} >"$OUT.tmp"
mv "$OUT.tmp" "$OUT"
echo "wrote $OUT ($(grep -c 'static const' "$OUT") shaders)"
