#!/usr/bin/env bash
# Build real AOT title archives from a reviewed local inventory and prepared GPU.
# No deployment. Game-derived inputs and artifacts remain under ignored build/.
set -euo pipefail
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
if [[ $# -lt 4 || $# -gt 5 ]]; then
    echo 'usage: tools/build_ps5_archives.sh INVENTORY XENOS_SOURCE SDK XMA_PREFIX [OUTPUT]' >&2
    exit 2
fi
work=$(realpath -- "$1")
xenos=$(realpath -- "$2")
sdk=$(realpath -- "$3")
codec=$(realpath -- "$4")
out=$(realpath -m -- "${5:-$root/build/prime-shared-ps5}")
[[ $out == "$root"/build/* ]] || { echo 'BLOCKED: output must be inside R-comp/build' >&2; exit 2; }
[[ -f $work/plain.xex && -d $work/ppc && -f $xenos/src/graphics/vulkan/command_processor.cpp ]] ||
    { echo 'BLOCKED: missing local inventory or prepared Xenos source' >&2; exit 2; }
[[ -x $sdk/bin/prospero-clang && -f $codec/lib/libavcodec.a && -f $codec/lib/libavutil.a ]] ||
    { echo 'BLOCKED: missing SDK or actual XMA codec archives' >&2; exit 2; }
mkdir -p -- "$out"
if [[ ${RCOMP_EXPLORATORY_INVENTORY:-0} == 1 ]]; then
    # Apply the existing strict diagnostic input checks. Only known, listed
    # missing functions are allowed; their fatal-on-call runtime behavior stays.
    # Keep the production gate and game-derived inventory unchanged.
    PYTHONPATH="$root/tools${PYTHONPATH:+:$PYTHONPATH}" python3 - "$work" "$out" <<'PY'
import json, sys
from pathlib import Path
from host_title_diagnostic import validate_inventory
try:
    report = validate_inventory(Path(sys.argv[1]))
except (OSError, ValueError, TypeError, KeyError) as error:
    raise SystemExit('BLOCKED: ' + str(error))
report['scope'] = 'exploratory PS5 archive input integrity; not deployment authorization'
Path(sys.argv[2], 'ARCHIVE_INPUTS.json').write_text(json.dumps(report, indent=2) + '\n')
print('PASS: input integrity; production gate ' + report['production_gate'] + '; PS5 execution NOT TESTED')
PY
else
    python3 "$root/tools/m6_boot_gate.py" "$work"
fi
# AOT modules (rcomp/aot_modules.h): app/m6 compiles every modules/<key>/ the inventory wrote next to the
# main module. Bind them to inventory.json before compiling: same module set, same generated bytes.
PYTHONPATH="$root/tools${PYTHONPATH:+:$PYTHONPATH}" python3 - "$work" <<'PY'
import hashlib, json, sys
from pathlib import Path
from m6_boot_gate import artifact_snapshot
work = Path(sys.argv[1])
report = json.loads((work / 'inventory.json').read_text(encoding='utf-8'))
listed = [m for m in ((report.get('modules') or {}).get('aot') or []) if m.get('descriptor')]
on_disk = sorted(p.parent.name for p in work.glob('modules/*/aot_module.cpp'))
if bool(listed) != (work / 'aot_modules.cpp').is_file() or on_disk != sorted(m['key'] for m in listed):
    raise SystemExit('BLOCKED: AOT modules on disk disagree with inventory.json')
for m in listed:
    folder = work / m['dir']
    try:
        actual = artifact_snapshot(folder)
    except (OSError, ValueError) as error:
        raise SystemExit('BLOCKED: AOT module ' + m['disc_path'] + ': ' + str(error))
    descriptor = folder / 'aot_module.cpp'
    actual['aot_module.cpp'] = {'bytes': descriptor.stat().st_size,
                                'sha256': hashlib.sha256(descriptor.read_bytes()).hexdigest()}
    if actual != m.get('artifacts'):
        raise SystemExit('BLOCKED: AOT module ' + m['disc_path'] + ' changed after the inventory')
if listed:
    print('PASS: %d AOT module(s) bound to inventory.json: %s' % (len(listed), ', '.join(m['disc_path'] for m in listed)))
PY
cmake -S "$root/app/m6" -B "$out" -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$root/cmake/toolchains/ps5.cmake" -DRCOMP_PS5_SDK="$sdk" \
    -DCMAKE_AR="$(command -v llvm-ar)" -DCMAKE_RANLIB="$(command -v llvm-ranlib)" \
    -DCMAKE_C_COMPILER_AR="$(command -v llvm-ar)" -DCMAKE_CXX_COMPILER_AR="$(command -v llvm-ar)" \
    -DCMAKE_C_COMPILER_RANLIB="$(command -v llvm-ranlib)" -DCMAKE_CXX_COMPILER_RANLIB="$(command -v llvm-ranlib)" \
    -DRCOMP_ROOT="$root" -DM6_WORK="$work" -DREXGLUE_SRC="$xenos" \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=Release -DRCOMP_XENOS_VULKAN=ON \
    -DRCOMP_M6_GENERATED_OPT="${RCOMP_GENERATED_OPT:--O2}" -DRCOMP_M6_CHECKED_ACCESS=OFF -DRCOMP_M6_FUNCTION_RING=OFF \
    -DCMAKE_C_FLAGS="${RCOMP_TLS_FLAGS:-}" -DCMAKE_CXX_FLAGS="${RCOMP_TLS_FLAGS:-}" \
    -DRCOMP_CPU_DIAGNOSTICS=OFF -DRCOMP_RUNTIME_DIAGNOSTICS=OFF \
    -DRCOMP_XENOS_DIAGNOSTICS=OFF -DRCOMP_XENOS_PROFILE_TIMINGS=OFF \
    -DRCOMP_XMA_FFMPEG_ROOT="$codec" -DRCOMP_XMA_DECODER_DIAGNOSTICS=OFF \
    -DRCOMP_M6_TIMEBASE_OBSERVER="${RCOMP_M6_TIMEBASE_OBSERVER:-OFF}" \
    -DRCOMP_M6_NATIVE_AUDIO_PROBE="${RCOMP_M6_NATIVE_AUDIO_PROBE:-OFF}" \
    -DRCOMP_M6_DIRECT_GUEST_PRESENTATION=ON \
    -DRCOMP_M6_DRAW_RESOLUTION_SCALE="${RCOMP_M6_DRAW_RESOLUTION_SCALE:-1}" \
    -DRCOMP_XENOS_RENDER_DIAGNOSTICS=OFF \
    -DRCOMP_M6_RENDER_DIAGNOSTICS_START_FRAME=7000 \
    -DRCOMP_M6_DIAGNOSTIC_HEADLESS=ON \
    -DRCOMP_M6_GAME_ROOT_PATH="${RCOMP_M6_GAME_ROOT_PATH:-/app0/game}" \
    > "$out/configure.log" 2>&1 || { tail -60 "$out/configure.log" >&2; exit 1; }
if [[ ${RCOMP_CONFIGURE_ONLY:-0} == 1 ]]; then
    printf 'PASS: configured actual PS5 archive targets in %s; compilation and execution NOT TESTED\n' "$out"
    exit 0
fi
cmake --build "$out" --target rcomp_m6_title rcomp_m6_generated -j"${RCOMP_BUILD_JOBS:-8}" \
    > "$out/build.log" 2>&1 || { tail -60 "$out/build.log" >&2; exit 1; }
printf 'PASS: PS5 archives compiled in %s; title link and execution NOT TESTED\n' "$out"
